"""One-off historical backfill: discover NEW CT Atlas events from the past
BACKFILL_WINDOW_DAYS days using ONLY GDELT DOC 2.0 and ACLED (via Google
News), without re-running Google News/official-source collection for
anything else. This is deliberately narrower than collector.py's own
COLLECTION_MODE=backfill (which re-queries every source across every
language) -- it exists specifically to add historical coverage from these
two newly-added sources without the cost of a full backfill.

Existing events are left completely untouched; only genuinely new events
(after the same real dedup + Gemini relevance pipeline the daily collector
uses) are appended to events.json. trend_summary/weekly_analysis are never
regenerated by this script.

Usage: GEMINI_API_KEY=... python tools/backfill_gdelt_acled.py
Env overrides:
  BACKFILL_WINDOW_DAYS (default 180) -- how far back to look.
  BACKFILL_CHUNK_DAYS (default 30) -- size of each GDELT date-range slice.
    GDELT caps a single query at GDELT_DOC_RESULTS_PER_QUERY results
    regardless of window length, so the window is sliced into chunks to get
    more thorough historical coverage than one snapshot for the whole
    window would give.
  BACKFILL_MAX_CALLS (default 200) -- safety cap on Gemini selection calls
    this run; re-run the script to continue if it stops early. Progress is
    cached in ai_article_selection_cache.json exactly like the daily
    collector, so a re-run picks up where this one left off.
"""

import os
import sys
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import collector  # noqa: E402  (reuses the real collection/dedup/AI-selection pipeline)

WINDOW_DAYS = int(os.getenv("BACKFILL_WINDOW_DAYS", "180"))
CHUNK_DAYS = int(os.getenv("BACKFILL_CHUNK_DAYS", "30"))
MAX_CALLS = int(os.getenv("BACKFILL_MAX_CALLS", "200"))


def gdelt_date_chunks(window_days, chunk_days):
    now = datetime.now(timezone.utc)
    start_of_window = now - timedelta(days=window_days)
    chunks = []
    cursor = start_of_window
    while cursor < now:
        chunk_end = min(cursor + timedelta(days=chunk_days), now)
        chunks.append((cursor, chunk_end))
        cursor = chunk_end
    return chunks


def collect_gdelt_backfill():
    categories = list(collector.CATEGORIES.keys())
    chunks = gdelt_date_chunks(WINDOW_DAYS, CHUNK_DAYS)
    total_queries = len(categories) * len(chunks)
    print(f"GDELT DOC 2.0 backfill: {len(categories)} categories x {len(chunks)} "
          f"date chunk(s) = {total_queries} queries")

    records = []
    query_number = 0
    for category in categories:
        for start_dt, end_dt in chunks:
            query_number += 1
            print(f"[GDELT {query_number}/{total_queries}] {category} "
                  f"{start_dt.date()} -> {end_dt.date()}")
            results = collector.collect_gdelt_category_query(
                category, start_dt=start_dt, end_dt=end_dt
            )
            records.extend(results)
            print(f"   accepted -> {len(results)}")
            if query_number < total_queries:
                time.sleep(collector.GDELT_DOC_QUERY_SPACING_SECONDS)

    print(f"GDELT DOC 2.0 backfill total: {len(records)}")
    return records


def collect_acled_backfill():
    acled_source = next(
        (s for s in collector.TARGETED_SOURCE_SITES if s["name"] == "ACLED"), None
    )
    if not acled_source:
        print("ACLED source entry not found in TARGETED_SOURCE_SITES; skipping.")
        return []

    queries = collector.targeted_source_queries(acled_source)
    records = []
    for query_number, query in enumerate(queries, start=1):
        print(f"[ACLED {query_number}/{len(queries)}] {query}")
        results = collector.collect_broad_query(
            query,
            WINDOW_DAYS,
            label="ACLED",
            acquisition_channel="targeted_source_query",
            targeted_source="ACLED",
            targeted_source_kind=acled_source["kind"],
        )
        records.extend(results)
        print(f"   accepted -> {len(results)}")

    print(f"ACLED backfill total: {len(records)}")
    return records


# ----------------------------------------------------------------------
# Gemini selection call-budget guard.
#
# Mirrors tools/run_collector_quota_safe.py's monkey-patch pattern, scoped
# down to just what this one-off script needs: cap Gemini selection calls
# and stop cleanly (ai_select_events returns None, matching how collector.py
# main() itself handles a budget/quota stop) so a re-run can continue from
# cached progress. Unlike the daily wrapper, this script does NOT touch
# prune()/trend/weekly regeneration -- those are intentionally left alone.
# ----------------------------------------------------------------------

_calls = 0
_real_post = collector.requests.post


def _is_selection_call(kwargs):
    body = kwargs.get("json")
    if not isinstance(body, dict):
        return False
    instruction = str(body.get("system_instruction", "")).lower()
    if "final editorial relevance filter" in instruction:
        return True
    schema = (body.get("response_format") or {}).get("schema", {})
    return isinstance(schema, dict) and "results" in schema.get("properties", {})


def _guarded_post(url, *args, **kwargs):
    global _calls
    if "generativelanguage.googleapis.com" in str(url) and _is_selection_call(kwargs):
        if _calls >= MAX_CALLS:
            raise collector.AISelectionQuotaError(
                f"Backfill self-imposed selection budget reached ({MAX_CALLS} calls). "
                "Re-run this script to continue."
            )
        _calls += 1
    return _real_post(url, *args, **kwargs)


collector.requests.post = _guarded_post


def main():
    db = collector.load_database_strict()
    existing_events = db["events"]
    print(f"Existing events in database: {len(existing_events)}")

    fresh = collect_gdelt_backfill() + collect_acled_backfill()
    print(f"\nTotal raw candidate records (GDELT + ACLED): {len(fresh)}")

    fresh = collector.exclude_reviewed_articles(fresh, existing_events)
    print(f"After excluding already-reviewed articles: {len(fresh)}")

    if not fresh:
        print("Nothing new to review. Database left untouched.")
        return

    fresh_clusters = collector.deduplicate_events(fresh)
    print(f"Candidate event clusters after dedup: {len(fresh_clusters)}")

    selected_fresh = collector.ai_select_events(fresh_clusters)

    if selected_fresh is None:
        print("\nGemini selection budget reached before finishing this backfill.")
        print(f"Cached progress preserved in {collector.AI_SELECTION_CACHE_FILE}; "
              "re-run this script to continue.")
        print("events.json has NOT been modified this run.")
        raise SystemExit(75)

    print(f"Gemini selected {len(selected_fresh)}/{len(fresh_clusters)} "
          "candidate event clusters.")

    selected_fresh = collector.deduplicate_events(selected_fresh)
    print(f"Post-translation event clusters: {len(selected_fresh)}")

    merged_events = collector.deduplicate_incremental(existing_events, selected_fresh)
    merged_events = collector.prune_old(merged_events)
    merged_events.sort(key=lambda e: e.get("published", ""), reverse=True)

    added = len(merged_events) - len(existing_events)
    print(f"\nNet new events added to the database: {added}")

    if added <= 0:
        print("No net-new events after dedup/merge; leaving events.json untouched.")
        return

    db["events"] = merged_events
    collector.atomic_json_write(collector.OUTPUT_FILE, db)
    print(f"{collector.OUTPUT_FILE} written with {added} new event(s) from "
          "GDELT DOC 2.0 + ACLED. trend_summary/weekly_analysis left untouched.")


if __name__ == "__main__":
    main()
